### ISSUE TITLE
mongo express simple access does not work anymore

### ISSUE THREAD

**Issue by Verizane** [mongo-express/mongo-express-docker#105]
Hi,

before I used the following compose to start a simple mongo-express and mongodb setup for local usage:

```
version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
```

up until now it was working as expected, I could use the mongo express to access the database information without authentication.

Now a colleague and I tried it again with clean images and it does not work anymore.

Has the default authentication changed?
