### ISSUE TITLE
Replace `ME_CONFIG_MONGODB_SERVER` with `ME_CONFIG_MONGODB_URL`

### ISSUE THREAD

**Issue by rtritto** [mongo-express/mongo-express-docker#113]
Environment variables `ME_CONFIG_MONGODB_SERVER` and `ME_CONFIG_MONGODB_PORT` were removed (in favor of `ME_CONFIG_MONGODB_URL`) in https://github.com/mongo-express/mongo-express/pull/957.
The retry logic introduced in #43 use the environment variables `ME_CONFIG_MONGODB_SERVER` and `ME_CONFIG_MONGODB_PORT` and needs to be replaced with `ME_CONFIG_MONGODB_URL`.

**Comment by BlackthornYugen** [comment]
Is this bug also related to why $host isn't getting set correctly? 

![image](https://github.com/mongo-express/mongo-express-docker/assets/3138467/d01f350f-d8a0-4ea8-a730-381760ced1d8)

**Comment by BlackthornYugen** [comment]
If I set both `ME_CONFIG_MONGODB_SERVER` and `ME_CONFIG_MONGODB_URL` it's fine though. 

```yaml
version: '3.3'

services:
    mongo:
        image: mongo:4

    mongoexpress:
        image: mongo-express:latest
        ports:
            - "8081:8081"
        links:
            - mongo
        environment: 
            - ME_CONFIG_MONGODB_SERVER=mongo
            - ME_CONFIG_MONGODB_URL=mongodb://mongo:27017
```

![image](https://github.com/mongo-express/mongo-express-docker/assets/3138467/df1960c0-9511-4a5a-b5ca-5b603f21a585)
