### ISSUE TITLE
Enable to connect to my MongoDB Atlas cluster

### ISSUE THREAD

**Issue by mathieu-benoit** [mongo-express/mongo-express-docker#119]
I'm doing:
```
cat EOF>>
services:
    mongo-express:
        image: mongo-express
        restart: always
        environment:
            - ME_CONFIG_MONGODB_URL=mongodb+srv://<username-redacted>:<password-redacted>@<server-redacted>.mongodb.net/?retryWrites=true&w=majority
        ports:
          - "8081:8081"
EOF
docker compose up -d
```
But as soon as I hit the endpoint, if I look at the logs of my runnign container, I'm getting:
```
Waiting for <server-redacted>.mongodb.net:27017...
/docker-entrypoint.sh: line 15: <server-redacted>.mongodb.net: Name has no usable address
/docker-entrypoint.sh: line 15: /dev/tcp/<server-redacted>.mongodb.net/27017: Invalid argument
Sat Jan 13 21:32:40 UTC 2024 retrying to connect to <server-redacted>.mongodb.net:27017 (2/10)
/docker-entrypoint.sh: line 15: <server-redacted>.mongodb.net: Name has no usable address
/docker-entrypoint.sh: line 15: /dev/tcp/<server-redacted>.mongodb.net/27017: Invalid argument
...<redacted>...
Sat Jan 13 21:32:48 UTC 2024 retrying to connect to <server-redacted>.mongodb.net:27017 (10/10)
/docker-entrypoint.sh: line 15: <server-redacted>.mongodb.net: Name has no usable address
/docker-entrypoint.sh: line 15: /dev/tcp/<server-redacted>.mongodb.net/27017: Invalid argument
```

Am I missing anything?

**Comment by BlackthornYugen** [comment]
Could this be a dns issue? Can you test if the message is different if you specify the server by IP address? Or you can ping from the container to make sure dns is working. `docker run -it --rm mongo-express ping something.mongodb.net`

**Comment by mathieu-benoit** [comment]
Not sure how to get the server IP address.

I just tested:
- Locally, `ping <server-redacted>.mongodb.net`, getting: `No address associated with hostname`
- `docker run -it --rm mongo-express ping <server-redacted>.mongodb.net`, getting `bad address`

**Comment by mathieu-benoit** [comment]
And for your information, if instead I do:
```
services:
  myapplication:
    image: mongodb/mongodb-community-server:latest
    environment:
      - CONN_STR=mongodb+srv://<username-redacted>:<password-redacted>@<server-redacted>.mongodb.net/?retryWrites=true&w=majority
    command: '/bin/bash -c "sleep 5; mongosh $$CONN_STR --eval \"show dbs;\""'
```
It's apparently working successfully:
````
Current Mongosh Log ID: 65a30858d6a2d3c3fe88995e
Connecting to:          mongodb+srv://<credentials>@<server-redacted>.mongodb.net/?retryWrites=true&w=majority&appName=mongosh+2.1.1
Using MongoDB:          6.0.12
Using Mongosh:          2.1.1

For mongosh info see: https://docs.mongodb.com/mongodb-shell/


To help improve our products, anonymous usage data is collected and sent to MongoDB periodically (https://www.mongodb.com/legal/privacy-policy).
You can opt-out by running the disableTelemetry() command.

admin  336.00 KiB
local    3.22 GiB
```
