### ISSUE TITLE
ME_CONFIG_MONGODB_URL_FILE

### ISSUE THREAD

**Issue by eviltik** [mongo-express/mongo-express-docker#123]
Hi !

It seem's that we can not use ME_CONFIG_MONGODB_URL_FILE + docker secrets.

My docker compose:

```
version: '3.7'

services:
  mongodbexpress:
    container_name: mongodbexpress
    build:
      context: ../mongodb-express
      dockerfile: ./docker/Dockerfile.dev
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_URL_FILE: /run/secrets/mongodb_url
      ME_CONFIG_MONGODB_BASICAUTH_USERNAME: xxx
      ME_CONFIG_MONGODB_BASICAUTH_PASSWORD: xxx
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
    secrets:
      - mongodb_url
    networks:
      - db_network

secrets:
  mongodb_url:
    file: ../../.secrets/dev/mongodb_url

networks:
  db_network:
```

Env vars after mongodb-express started:

```
ME_CONFIG_SITE_SESSIONSECRET=secret
ME_CONFIG_BASICAUTH=true
ME_CONFIG_MONGODB_ENABLE_ADMIN=true
ME_CONFIG_MONGODB_URL_FILE=/run/secrets/mongodb_url
ME_CONFIG_MONGODB_URL=mongodb://mongo:27017
ME_CONFIG_MONGODB_BASICAUTH_USERNAME=xxx
ME_CONFIG_MONGODB_BASICAUTH_PASSWORD=xxx
```

Error:
```
Could not connect to database using connectionString: mongodb://mongo:27017"
```

Expected:
* no error, use the mongodb url from /run/secrets/mongodb_url
