### ISSUE TITLE
Mongo-express docker fails to connect to Mongo docker if DB volume is mounted

### ISSUE THREAD

**Issue by ruslaniv** [mongo-express/mongo-express-docker#39]
I have this docker-compose file:

```
version: '3.7'
services:
  db-mongo:
    image: mongo
    container_name: db-mongo
  environment:
      - MONGO_INITDB_DATABASE=auth
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=pass
  volumes:
     - /Users/John/Documents/Docker/mongoDB/db-mongo:/data/db
   ports:
      - '27017:27017'
  db-mongo-admin:
    image: mongo-express
    container_name: db-mongo-admin
    depends_on:
      - db-mongo
    environment:
      - ME_CONFIG_MONGODB_SERVER=db-mongo
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=fairlylongpassword
    ports:
      - '8081:8081'
```
When i start it up, it fails with 
```
...
Mon Jan 27 06:11:19 UTC 2020 retrying to connect to db-mongo:27017 (5/5)
/docker-entrypoint.sh: connect: Connection refused
/docker-entrypoint.sh: line 14: /dev/tcp/db-mongo/27017: Connection refused
Welcome to mongo-express
------------------------
/node_modules/mongodb/lib/server.js:265
        process.nextTick(function() { throw err; })
                                      ^
MongoError: failed to connect to server [db-mongo:27017] on first connect
...
```
But if I remove the bind mount from the Mongo container, **without changing anything else**, both containers start fine and I can use mongo-express to log to the DB.
