### ISSUE TITLE
Could not connect to database using connectionString: mongodb://mongo:27017"

### ISSUE THREAD

**Issue by jrujano** [mongo-express/mongo-express-docker#67]
Trying in different ways I have not been able to connect to my mongodb through mongo-express

![Selección_136](https://user-images.githubusercontent.com/7560024/124540606-c494b600-dded-11eb-892e-19cd008aae14.png)

![Selección_137](https://user-images.githubusercontent.com/7560024/124540884-4b499300-ddee-11eb-9007-1d09c8af3d91.png)

**Comment by thomas-hofmann-dci** [comment]
same result withing the following environment:
Latest (as of now) mongo-express and mongo (4.4-bionic and latest) docker-images.

sample "docker-compose.yml":
```
services:

  mongo:
    image: mongo #:4.4-bionic
   
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

    # optionally make it available to the outside
    ports:
      - "27017:27017" 

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
```

**Comment by JafarAkhondali** [comment]
@thomas-hofmann-dci Try connect using `ME_CONFIG_MONGODB_URL`

**Comment by mtwinux** [comment]
Same error here. Tried a few config. Event the docker-compose.yml on the main page of mongo (https://hub.docker.com/_/mongo) leads to the same error.

The only way to get this working is to set the 0.54.0 tag version : 

version: "3.7"
services:
  mongodb:
    container_name: mongo-dev
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_DATABASE=auth
      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - '27017:27017'
  mongo-express:
    container_name: mongo-express
    image: mongo-express**:0.54.0**
    depends_on:
      - mongodb
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
      - ME_CONFIG_MONGODB_SERVER=mongo-dev
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=ihavealongpassword
    ports:
      - '8081:8081'

**Comment by JafarAkhondali** [comment]
@mtwinux  The page on dockerhub is outdated, as of version 1, you should use `ME_CONFIG_MONGODB_URL`, if for some reason you don't want to, you'll have to use version 0.X

**Comment by gBusato** [comment]
This configuration should work: 

version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: "mongodb://root:example@mongo:27017/"
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

**Comment by m-ocean-it** [comment]
In my case, I had to either run `docker-compose` twice or manually create a desired network before running `docker-compose`. It's like the network was not managing to get created fast enough for containers to utilize it right away. Although, using `restart: always` didn't work, so... I don't really know what's going on.

Until finding the described solution, I tried restarting the Docker daemon and rebooting my machine, both actions did nothing.

**Comment by psoder** [comment]
> How can I share code here? The format looks bad.

@wbqtac to format code in blocks wrap it in `` ` `` (backticks).

If you only want to include something inline, like `this`, the syntax is `` `<text goes here>` ``

For full code blocks use:
````
```<language goes here (e.g. java or cpp)>
<code goes here>
```
````
For example:
````
```kotlin
println("Hello World!")
```
````
will display,
```kotlin
println("Hello World!")
```

See GitHub's [formatting guide](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) for more details.

**Comment by johurul000** [comment]
As of today using an image of mongo-express version 0.54.0 Works for me.

The is my .yaml file
```yaml
version: '3'
services: 
  mongodb:
    image:  mongo:4.4.17-focal
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
  mongo-express:
    image: mongo-express:0.54.0
    restart: always
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
```

**Comment by siddharthans2000** [comment]
> As of today using an image of mongo-express version 0.54.0 Works for me.
> 
> The is my .yaml file
> 
> ```yaml
> version: '3'
> services: 
>   mongodb:
>     image:  mongo:4.4.17-focal
>     container_name: mongodb
>     ports:
>       - 27017:27017
>     environment:
>       - MONGO_INITDB_ROOT_USERNAME=admin
>       - MONGO_INITDB_ROOT_PASSWORD=password
>   mongo-express:
>     image: mongo-express:0.54.0
>     restart: always
>     container_name: mongo-express
>     ports:
>       - 8081:8081
>     environment:
>       - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
>       - ME_CONFIG_MONGODB_ADMINPASSWORD=password
>       - ME_CONFIG_MONGODB_SERVER=mongodb
> ```

Yeah thanks this works for me too, but still haven't able to figure it out why it is showing error with the latest packages

**Comment by Nischal2015** [comment]
This is what worked for me
```
version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 8081:8081
    depends_on:
      - mongodb
    restart: always
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
```

**Comment by TESLAOPUnix** [comment]
I also have same issue with this currently trying using cli now I guess compose is the only option

**Comment by maddes-b** [comment]
The documentation on Docker Hub is outdated: see https://github.com/mongo-express/mongo-express/issues/1414 and #106
After 1.0 the usage of `ME_CONFIG_MONGODB_SERVER` has been changed, normally you will use `ME_CONFIG_MONGODB_URL` now, e.g. with `mongodb://admin:password@mongodb:27017`

Make sure to read the README here on GitHub regarding the tag you are using.

**Comment by ademaldemir** [comment]
add this env param to mongo-express
ME_CONFIG_BASICAUTH: false
It worked for me! 🚀

**Comment by InWamos** [comment]
### The following worked for me on Debian 12 

But despite the config, it still creates a default admin user with the following credentials: 
admin
pass
Docker logs for this:
```mongo_ui  | basicAuth credentials are "admin:pass", it is recommended you change this in your config.js!```
```yml
services:

  mongo:
    image: mongo:6
    restart: always
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./db_data/:/data/db/
      - /etc/timezone:/etc/timezone:ro
      #   remain this only if you want a mongoDB to be accesible from your LAN
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    container_name: mongo_ui
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
```

Run with:
```sudo docker compose up -d```
from a directory with the .yml file
